version: '2'
services:
  zookeeper-t:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-t:
    # build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - "zookeeper-t:zookeeper-t"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-t:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

